### ISSUE TITLE
No setup.py, How to install?

### ISSUE THREAD

**Issue by wyrdash** [teogramm/KOtoZotero#1]
This project seems very useful to me, especially with Zotero 7's EPUB reader. However, I cannot figure out how to install this as there is no setup.py, how should I install this program? I'm on Windows if that matters.

Thanks.

**Comment by teogramm** [comment]
Just download the repo in a folder, install the requirements.txt file and run ``python 3 -m kotozotero``. You don't need to actually install anything.
